### ISSUE TITLE
`TypeError: cannot pickle '_thread.lock' object` on boot when combining `--ipa` and `-j`

### ISSUE THREAD

**Issue by hafeoz** [9001/copyparty#113]
**Describe the bug**
`copyparty` crashes on start when combining `--ipa` ("only accept connections from IP-addresses inside CIDR") and `-j` ("max num cpu cores")

**To Reproduce**
1. `copyparty --ipa 10.89.0.0/16 -j0`
2. Observe:
```
copyparty v1.15.9 "fill the drives" (2024-10-18)
  CPython v3.12.7 on Linux64  [GCC 14.2.0]
   sqlite 3.47.0*1 | jinja 3.1.4 | pyftpd (None) | tftp (None)

2024-10-25
16:11:07.376 root                  multithreading enabled with -j 0, so disabling fpool -- this can reduce upload performance on some filesystems
16:11:07.376 root                  opening sessions-db /root/.config/copyparty/sessions.db
16:11:07.377 auth                  volumes and permissions:

"/"  /root
|    read:  everybody
|   write:  everybody
|    move:  --none--
|  delete:  --none--
|    dots:  --none--
|     get:  --none--
|   upGet:  --none--
|    html:  --none--
|  uadmin:  --none--

16:11:07.377 auth                  hint: enable searching and upload-undo with argument -e2dsa
16:11:07.377 auth                  hint: enable upload deduplication with --dedup (but see readme for consequences)
16:11:07.377 auth                  anyone can write to the current directory: /root

16:11:07.377 root                  max clients: 1024
16:11:07.379 tcpsrv                available @  http://127.0.0.1:3923/  (1-lo)
16:11:07.379 tcpsrv                available @  http://[::1]:3923/  (1-lo)

16:11:07.380 dependencies          OK: sqlite, pillow, vips, pillow-webp, ffmpeg, ffprobe, mutagen, NG: argon2, pillow-heif, pillow-avif, see --deps
16:11:07.380 thumb                 decoder preference: vips, pil, ff
16:11:07.394 broker                booting 32 subprocesses
Traceback (most recent call last):
  File "/usr/local/bin/copyparty", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/copyparty/__main__.py", line 1783, in main
    SvcHub(al, dal, argv, "".join(printed)).run()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/copyparty/svchub.py", line 373, in __init__
    self.broker = Broker(self)
                  ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/copyparty/broker_mp.py", line 51, in __init__
    proc.start()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/context.py", line 289, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.12/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
```

**Server details**
```
copyparty v1.15.9 "fill the drives" (2024-10-18)
  CPython v3.12.7 on Linux64  [GCC 14.2.0]
   sqlite 3.47.0*1 | jinja 3.1.4 | pyftpd (None) | tftp (None)
```

**Additional context**
Running without either `--ipa` or `-j` works fine.

This bug probably presents for several versions - I've just updated from an ancient version and it starts crashing. A downgrade to `1.15.8` does not fix the issue.

**Comment by 9001** [comment]
Yup, sorry about this... The issue was reported on discord and fixed in 3a0d882c5e428343b2ec346f8ac1c80249546ca7 , but that hasn't become part of a release yet.

I was hoping to find a fix for #110 first, but if the latest beta I posted in that issue still does not fix it, then I think it is time to give up.

Right now I am not sure when I will be able to make a new release to fix this issue, but I hope to find some time on Sunday.
